export const TaskPlatformList = [
    {
        id: 1,
        title: 'Twitter',
        src: '/images/twitter.svg',
        width: 19,
        height: 16,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Follow',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Username',
                name: 'twitter.follow',
            },
            {
                title: 'Like',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Tweet URL',
                name: 'twitter.like',
            },
            {
                title: 'Retweet',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Tweet URL',
                name: 'twitter.retweet',
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Tweet URL',
                name: 'twitter.comment',
            },
            {
                title: 'Tag friends',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Tweet URL',
                name: 'twitter.tagFriends',
            },
            {
                title: 'Enable Notifications',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Tweet URL',
                name: 'twitter.enable_notifications',
            },
            {
                title: 'Drop ETH Wallet',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Tweet URL',
                name: 'twitter.ethWallet',
            },
        ],
    },
    {
        id: 2,
        title: 'Website',
        src: '/images/website.svg',
        width: 19,
        height: 19,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: true,
        inputFields: [
            {
                title: 'Sign Up',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Custom URL',
                name: 'website.signUp',
            },
            {
                title: 'Fill your email',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Custom URL',
                name: 'website.fillYourEmail',
            },
        ],
    },
    {
        id: 3,
        title: 'Daily Task',
        src: '/images/daily-reward.svg',
        width: 18,
        height: 18,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Come back every day',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Website URL',
                name: 'daily_task.comeback_everyday',
            },
        ],
    },
    {
        id: 4,
        title: 'Discord',
        src: '/images/discord.svg',
        width: 16,
        height: 18,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Join',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Invitation URL',
                name: 'discord.join',
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Group URL',
                name: 'discord.comment',
            },
            {
                title: 'Enable Notifications',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Group URL',
                name: 'discord.enable_notifications',
            },
        ],
    },
    {
        id: 5,
        title: 'Instagram',
        src: '/images/instagram.svg',
        width: 20,
        height: 20,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Subscribe',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Username',
                name: 'instagram.subscribe',
            },
            {
                title: 'Like',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'instagram.like',
            },
            {
                title: 'Retweet',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'instagram.retweet',
            },
            {
                title: 'Share',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'instagram.share',
            },
        ],
    },
    {
        id: 6,
        title: 'Referral',
        src: '/images/refer-friends.svg',
        width: 19,
        height: 13,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: true,
        inputFields: [
            {
                title: 'Invite friends to this contest',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Referral URL',
                name: 'referral.invite_friends',
            },
        ],
    },
    {
        id: 7,
        title: 'Telegram',
        src: '/images/telegram.svg',
        width: 18,
        height: 18,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Join',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Channel URL',
                name: 'telegram.join',
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Channel URL',
                name: 'telegram.comment',
            },
        ],
    },
    {
        id: 8,
        title: 'Reddit',
        src: '/images/reddit.svg',
        width: 20,
        height: 20,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Join',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Profile URL',
                name: 'reddit.join',
            },
            {
                title: 'Upvote',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'reddit.upvote',
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'reddit.comment',
            },
            {
                title: 'Share',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'reddit.share',
            },
            {
                title: 'Save',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'reddit.save',
            },
        ],
    },
    {
        id: 9,
        title: 'Snapchat',
        src: '/images/snapchat.svg',
        width: 20,
        height: 20,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Follow',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Profile URL',
                name: 'snapchat.follow',
            },
            {
                title: 'Like',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Snap URL',
                name: 'snapchat.like',
            },
            {
                title: 'Share',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Snap URL',
                name: 'snapchat.share',
            },
            {
                title: 'Remix',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Snap URL',
                name: 'snapchat.Remix',
            },
        ],
    },
    {
        id: 10,
        title: 'Linkedin',
        src: '/images/linkedin.svg',
        width: 19,
        height: 19,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Subscribe',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Page URL',
                name: 'linkedin.subscribe',
            },
            {
                title: 'Like',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'linkedin.like',
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'linkedin.comment',
            },
            {
                title: 'Share',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'linkedin.share',
            },
        ],
    },
    {
        id: 11,
        title: 'Tiktok',
        src: '/images/tiktok.svg',
        width: 17,
        height: 19,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Subscribe',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Profile URL',
                name: 'tiktok.subscribe',
            },
            {
                title: 'Watch',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Video URL',
                name: 'tiktok.watch',
            },
            {
                title: 'Like',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Video URL',
                name: 'tiktok.like',
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Video URL',
                name: 'tiktok.comment',
            },
            {
                title: 'Share',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Video URL',
                name: 'tiktok.share',
            },
            {
                title: 'Enable Notifications',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Profile URL',
                name: 'tiktok.enable_notifications',
            },
        ],
    },
    {
        id: 12,
        title: 'Youtube',
        src: '/images/youtube.svg',
        width: 20,
        height: 15,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Subscribe',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Channel URL',
                name: 'youtube.subscribe',
            },
            {
                title: 'Watch',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Video URL',
                name: 'youtube.watch',
            },
            {
                title: 'Like',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Video URL',
                name: 'youtube.like',
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Video URL',
                name: 'youtube.comment',
            },
            {
                title: 'Enable Notifications',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Channel URL',
                name: 'youtube.enable_notifications',
            },
        ],
    },
    {
        id: 13,
        title: 'Messenger',
        src: '/images/messenger.svg',
        width: 18,
        height: 18,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Join',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Invite URL',
                name: 'messenger.join',
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Profile URL',
                name: 'messenger.comment',
            },
            {
                title: 'Enable Notifications',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Profile URL',
                name: 'messenger.enable_notifications',
            },
        ],
    },
    {
        id: 14,
        title: 'Facebook',
        src: '/images/facebook.svg',
        width: 17,
        height: 18,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Subscribe',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Page URL',
                name: 'facebook.subscribe',
            },
            {
                title: 'Like',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'facebook.like',
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'facebook.comment',
            },
            {
                title: 'Share',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Post URL',
                name: 'facebook.share',
            },
        ],
    },
    {
        id: 15,
        title: 'Wechat',
        src: '/images/wechat.svg',
        width: 20,
        height: 16,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Join',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Invite URL',
                name: 'wechat.join',
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Profile URL',
                name: 'wechat.comment',
            },
            {
                title: 'Enable Notifications',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Profile URL',
                name: 'wechat.enable_notifications',
            },
        ],
    },
    {
        id: 16,
        title: 'Whatsapp',
        src: '/images/whatsapp.svg',
        width: 17,
        height: 17,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Join',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Invite URL',
                name:'whatsapp.join'
            },
            {
                title: 'Add',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Phone Number',
                name:'whatsapp.add'
            },
            {
                title: 'Message',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Phone Number',
                name:'whatsapp.message'
            },
            {
                title: 'Call',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Phone Number',
                name:'whatsapp.call'
            },
        ],
    },
    {
        id: 17,
        title: 'Twitch',
        src: '/images/twitch.svg',
        width: 16,
        height: 17,
        anyTaskSelected: false,
        isPlatformClicked: false,
        isPremium: false,
        inputFields: [
            {
                title: 'Join',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Live Video URL',
                name:'twitch.join'
            },
            {
                title: 'Subscribe',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Channel URL',
                name:'twitch.subscribe'
            },
            {
                title: 'Watch',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Video URL',
                name:'twitch.watch'
            },
            {
                title: 'Like',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Video URL',
                name:'twitch.like'
            },
            {
                title: 'Comment',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Video URL',
                name:'twitch.comment'
            },
            {
                title: 'Enable Notifications',
                isTitleClicked: false,
                isTaskAdded: false,
                placeholder: 'Channel URL',
                name:'twitch.enable_notifications'
            },
        ],
    },
];
